---
- name: Run PowerShell script on Windows
  hosts: win22  # Your target host
  gather_facts: false
  connection: winrm  # Or ssh if configured

  tasks:
    - name: Run dns.ps1 PowerShell script
      win_shell: |
        dns.ps1  # Just run the script, assuming it's available on the target machine
